# Generated by Django 2.1.2 on 2018-10-28 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181028_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='pesel',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers characters are allowed.')]),
        ),
    ]
