# Generated by Django 2.1.2 on 2018-11-24 18:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181028_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DonateBlood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers characters are allowed.')])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('blood', models.CharField(choices=[('ARh+', 'ARh+'), ('ARh-', 'ARh-'), ('BRh+', 'BRh+'), ('BRh-', 'BRh-'), ('ABRh+', 'ABRh+'), ('ABRh-', 'ABRh-'), ('0R+', '0R+'), ('ORH-', 'ORH-')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departure')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('blood', models.CharField(max_length=4)),
                ('donate_blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DonateBlood')),
            ],
        ),
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sample')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='donateblood',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
    ]
