# Generated by Django 2.1.2 on 2018-11-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181124_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblood',
            name='presence',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.Presence'),
            preserve_default=False,
        ),
    ]
