# Generated by Django 2.1.2 on 2018-11-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donateblood_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblood',
            name='worker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Worker'),
            preserve_default=False,
        ),
    ]
