# Generated by Django 2.1.2 on 2018-11-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181124_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='presence',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.Presence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donateblood',
            name='worker',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.Worker'),
            preserve_default=False,
        ),
    ]
