# Generated by Django 2.1.2 on 2018-11-24 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181124_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
