//WORKERS
export const FETCH_WORKERS = "FETCH_WORKERS";
export const GET_DATA_REQUESTED = 'GET_DATA_REQUESTED';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';

export const ADD_WORKER_SUCCESS = "ADD_WORKER";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER";
export const UPDATE_WORKER_SUCCESS = "UPDATE_WORKER";