export const GET_DATA_REQUESTED_WORKER = 'GET_DATA_REQUESTED_WORKER';
export const GET_DATA_FAILED_WORKER = 'GET_DATA_FAILED_WORKER';
export const FETCH_WORKERS = "FETCH_WORKERS";
export const ADD_WORKER_SUCCESS = "ADD_WORKER";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER";
export const UPDATE_WORKER_SUCCESS = "UPDATE_WORKER";

export const GET_DATA_REQUESTED_BLOOD = 'GET_DATA_REQUESTED_BLOOD';
export const GET_DATA_FAILED_BLOOD = 'GET_DATA_FAILED_BLOOD';
export const FETCH_BLOOD_TYPES = "FETCH_BLOOD_TYPES";
export const ADD_BLOOD_TYPE_SUCCESS = "ADD_BLOOD_TYPE_SUCCESS";
export const DELETE_BLOOD_TYPE_SUCCESS = "DELETE_BLOOD_TYPE_SUCCESS";
export const UPDATE_BLOOD_TYPE_SUCCESS = "UPDATE_BLOOD_TYPE_SUCCESS";

export const GET_DATA_REQUESTED_DEPARTURE = 'GET_DATA_REQUESTED_DEPARTURE';
export const GET_DATA_FAILED_DEPARTURE = 'GET_DATA_FAILED_DEPARTURE';
export const FETCH_DEPARTURES = "FETCH_DEPARTURES";
export const ADD_DEPARTURE_SUCCESS = "ADD_DEPARTURE_SUCCESS";
export const DELETE_DEPARTURE_SUCCESS = "DELETE_DEPARTURE_SUCCESS";
export const UPDATE_DEPARTURE_SUCCESS = "UPDATE_DEPARTURE_SUCCESS";

export const GET_DATA_REQUESTED_PATIENTS = 'GET_DATA_REQUESTED_PATIENTS';
export const GET_DATA_FAILED_PATIENTS = 'GET_DATA_FAILED_PATIENTS';
export const FETCH_PATIENTS = "FETCH_PATIENTS";
export const ADD_PATIENTS_SUCCESS = "ADD_PATIENTS_SUCCESS";
export const DELETE_PATIENTS_SUCCESS = "DELETE_PATIENTS_SUCCESS";
export const UPDATE_PATIENTS_SUCCESS = "UPDATE_PATIENTS_SUCCESS";

export const GET_DATA_REQUESTED_PRESENCE = 'GET_DATA_REQUESTED_PRESENCE';
export const GET_DATA_FAILED_PRESENCE = 'GET_DATA_FAILED_PRESENCE';
export const FETCH_PRESENCE = "FETCH_PRESENCE";
export const ADD_PRESENCE_SUCCESS = "ADD_PRESENCE_SUCCESS";
export const DELETE_PRESENCE_SUCCESS = "DELETE_PRESENCE_SUCCESS";
export const UPDATE_PRESENCE_SUCCESS = "UPDATE_PRESENCE_SUCCESS";

export const GET_DATA_REQUESTED_DONATION= 'GET_DATA_REQUESTED_DONATION';
export const GET_DATA_FAILED_DONATION = 'GET_DATA_FAILED_DONATION';
export const FETCH_DONATION = "FETCH_DONATION";
export const ADD_DONATION_SUCCESS = "ADD_DONATION_SUCCESS";
export const DELETE_DONATION_SUCCESS = "DELETE_DONATION_SUCCESS";
export const UPDATE_DONATION_SUCCESS = "UPDATE_DONATION_SUCCESS";

export const GET_DATA_REQUESTED_RESOURCES = 'GET_DATA_REQUESTED_RESOURCES';
export const GET_DATA_FAILED_RESOURCES = 'GET_DATA_FAILED_RESOURCES';
export const FETCH_RESOURCES = "FETCH_RESOURCES";