export const GET_DATA_REQUESTED = 'GET_DATA_REQUESTED';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';

export const FETCH_WORKERS = "FETCH_WORKERS";
export const ADD_WORKER_SUCCESS = "ADD_WORKER";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER";
export const UPDATE_WORKER_SUCCESS = "UPDATE_WORKER";

export const FETCH_BLOOD_TYPES = "FETCH_BLOOD_TYPES";
export const ADD_BLOOD_TYPE_SUCCESS = "ADD_BLOOD_TYPE_SUCCESS";
export const DELETE_BLOOD_TYPE_SUCCESS = "DELETE_BLOOD_TYPE_SUCCESS";
export const UPDATE_BLOOD_TYPE_SUCCESS = "UPDATE_BLOOD_TYPE_SUCCESS";
