# Generated by Django 2.1.2 on 2018-11-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181124_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblood',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='donateblood',
            name='presence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Presence'),
        ),
        migrations.AlterField(
            model_name='donateblood',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Worker'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Departure'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Worker'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='donate_blood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DonateBlood'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.Sample'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Worker'),
        ),
    ]
